### ISSUE TITLE
Support relative paths

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-go-ipfs-core#15]
The current path type doesn't support _relative_ paths. I'm not sure how best to do this or even if we _want_ to do this but, for now, symlink "targets" will have to just be arbitrary strings.

**Comment by magik6k** [comment]
How about a new type:

```go
type RelativePath interface {
  Path // Path methods resolve Base + Target

  // Target returns raw symlink target
  Target() string

  // Base return path of the symlink parent
  Base() Path
}
```

`RelativePath.Path.String()` would look roughly like this:
```go
func (relPath *relativePath) String() string {
  if path.IsAbs(relPath.target) {
    return relPath.target
  }
  return path.Join(relPath..base, relPath.target)
}
```

Thoughts?

cc @warpfork

**Comment by Stebalien** [comment]
That should cover much of it. Unfortunately, there's still the issue of _absolute_ symlinks. The current `Path` system assumes that all paths have a namespace. However, a symlink could point to `/usr/share/...`.

**Comment by magik6k** [comment]
Users could just use `.Target` in that case. Path methods would just yield invalid paths (we should somehow make them error, but things like:
```
type RelativePath interface {
  Path() (Path, error)
```

would make the interface less convenient.)

**Comment by Stebalien** [comment]
I agree. Really, my question is: "should `Symlink.Target` be a `Path` or just a string. I think the conclusion here is that it should just be a string.

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant. This issue has been merged with a few other issues, and moved to https://github.com/ipfs/boxo/issues/198.
