### ISSUE TITLE
Incorporate feedback from textile

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-go-ipfs-core#16]
Textile has defined a bunch of helper functions. We should take a look at these helpers and think through any changes we might want to make to the CoreAPI to simplify them.

Code: https://github.com/textileio/go-textile/blob/a7f7c040d2178a5768d4144f33afde38ee2129fd/ipfs/api.go

Looking through this, it looks like the main missing component is MFS support.

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc). General direction is to over time, merge the majority of kubo-specific parts of coreiface into kubo itself.

 In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo.  Please feel free to open a new issue in Kubo or Boxo (and reference this issue) if this is still relevant.

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
