### ISSUE TITLE
Remove hidden file handling

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-go-ipfs-core#17]
We should be able to handle this at the cmds (and maybe files) layer and filter hidden files out before they ever reach the CoreAPI. Does this make sense?

**Comment by magik6k** [comment]
It should be possible to implement this as a proxy files layer, that would make things much nicer in the adder code.

(also, with the current way it works, send hidden files to the daemon, just so they get dropped there)

**Comment by Stebalien** [comment]
Are you _sure_ we send hidden files? It looks like the commands library is dropping them, as far as I can tell.

**Comment by magik6k** [comment]
> It looks like the commands library is dropping them

Right, we do that (with a small bug - https://github.com/ipfs/go-ipfs-files/issues/11), and it makes things much easier if we don't care about handling `hidden` in http api - I removed all hidden file handling from CoreAPI and the command in 
https://github.com/ipfs/go-ipfs/pull/6019, and it still just works.

(If we want to remove hidden handling from http api, we'll probably need to adjust what js-ipfs does)

**Comment by Stebalien** [comment]
js-ipfs does it client-side as well.

**Comment by magik6k** [comment]
https://github.com/ipfs/go-ipfs/pull/6019
