### ISSUE TITLE
Move to directory.

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/interface-go-ipfs-core#2]
I think this repo might contain a bit more than just pure interface so moving the interface itself to a directory might be useful.

It will also sort out the directory name vs package name.

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc).

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
