### ISSUE TITLE
Drop error from ParsePath

### ISSUE THREAD

**Issue by magik6k** [ipfs/interface-go-ipfs-core#20]
Currently the `ParsePath` method returns an error, which makes using it a bit verbose:

```
p, err := api.ParsePath("/ipfs/QmThing")
if err != nil {
  [...]
}

_, err := api.Unixfs.Ls(ctx, p)
if err != nil {
  [...]
}
```

We could:
  * Let paths be arbitrary strings (behind an interface, because Go type system..)
  * Provide a `Validate(path) error` method to let users check their paths (also check them in places when it's really needed)
  * Drop `Namespace`/`Mutable` methods from the interface, move to global functions (possibly in a separate package)

This would look roughly like this for users:

```go
_, err := api.Unixfs.Ls(ctx, apipath.New("/ipfs/QmThing")) // checking still happens, but errors are returned from api.Unixfs.Ls
if err != nil {
  [...]
}
```

**Comment by Stebalien** [comment]
SGTM. Personally... I like all _absolute_ paths being namespaced but I can live with this.

**Comment by magik6k** [comment]
This doesn't drop the namespacing requirement, it just defers error handling

**Comment by Stebalien** [comment]
Yeah, that's probably the best for usability (although it would be nice to _return_ something a little more checked).
