### ISSUE TITLE
Conn().Streams() should return StreamInfo objects

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-go-ipfs-core#27]
We _currently_ just list the protocol but it would be nice to include things like direction as well.

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc).

 In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo.  Please feel free to open a new issue in Kubo or Boxo (and reference this issue).

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
