### ISSUE TITLE
Buffered operations

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-go-ipfs-core#31]
Our datastores can often improve the performance of batched operations. It would be nice if we could have some kind of `Buffered() *BufferedCoreAPI` function on the CoreAPI that returns a _buffered_ CoreAPI with special `Flush()` (and maybe `Close()`) function(s).

This could _also_ be done with transactions but:

1. It may be a while until we get to that point.
2. Transactions need to support Abort.

Thoughts? We could _also_ just add `PutAll` functions but buffering is probably the most friendly solution.

**Comment by magik6k** [comment]
This is going to be a bit tricky with the http client lib, but definitely doable. In go-ipfs we'd probably just wrap coreapi blockservice into the autobatch thing (which `add` does internally) and maybe optimize other things as needed.

Transactions don't really have apply to every coreapi operation IMO. Important areas for them would be pinning, ipns publishing and key management. In places where we just add immutable data, we can't really guarantee that some piece of data won't exist somewhere else in the network, so if an add operation fails we shouldn't have to remove already added data.

**Comment by Stebalien** [comment]
> This is going to be a bit tricky with the http client lib, but definitely doable.

We can be slow about implementing this in the http client. We can define:

```
type buffered struct {
  CoreAPI
}
```

And then slowly override different subsystems.

> so if an add operation fails we shouldn't have to remove already added data.

Yeah, you're right. And a transaction can auto-buffer internally to optimistically avoid writes in some cases.

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc).

 In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo.  Please feel free to open a new issue in Kubo or Boxo (and reference this issue).

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
