### ISSUE TITLE
ResolveComponents

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-go-ipfs-core#42]
We should have a `ResolveComponents(ctx, opts...) <-chan Result` function that resolves a path and returns each component as it's resolved.

Result would be:

```go
type Result struct {
   From Path
   To Path
}
```

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc). General direction is to merge majority of kubo-specific coreiface into kubo itself.

 In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo.  Please feel free to open a new issue in Kubo or Boxo (and reference this issue) if this is still relevant.

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
