### ISSUE TITLE
Any examples for Unixfs.Add?

### ISSUE THREAD

**Issue by daviddias** [ipfs/interface-go-ipfs-core#46]
Looking to figure out how to use it for:

- Adding a file
- Adding a file with trickle-dag
- Adding a directory
- Adding a directory with sharding

https://github.com/ipfs/interface-go-ipfs-core/blob/master/unixfs.go#L67-L68

**Comment by daviddias** [comment]
Answering to myself:


- Adding a file - https://github.com/ipfs/go-ipfs/tree/master/docs/examples/go-ipfs-as-a-library#part-2-adding-a-file-and-a-directory-to-ipfs
- Adding a file with trickle-dag - No example yet, but should be just passing the option to use the trickle dag layout with https://godoc.org/github.com/ipfs/interface-go-ipfs-core/options#UnixfsAddOption
- Adding a directory - https://github.com/ipfs/go-ipfs/tree/master/docs/examples/go-ipfs-as-a-library#part-2-adding-a-file-and-a-directory-to-ipfs
- Adding a directory with sharding - Still looking #48

**Comment by adgsm** [comment]
Adding to above question by @daviddias 

Are there any examples how to use [Unixfs.Add](https://github.com/ipfs/kubo/blob/1457b4fd4abff0bdcdccbacc26934cb7fa8e8a43/core/coreapi/unixfs.go#L59) with all three parameters supplied?

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc).

 In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo.  Please feel free to open a new issue in Boxo (and reference this issue), explaining what types of examples should be added to https://github.com/ipfs/boxo/tree/main/examples.

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
