### ISSUE TITLE
How to add files to MFS?

### ISSUE THREAD

**Issue by hacdias** [ipfs/interface-go-ipfs-core#53]
How can we add files to the MFS using this API?

**Comment by Stebalien** [comment]
You can't. We never finished adding the abstractions for that.

**Comment by hacdias** [comment]
@Stebalien I will work on adding the interfaces here and implementations on `go-ipfs`. Let me know if I can ping you when I have any doubts

**Comment by Stebalien** [comment]
Please do! And thanks for doing this!

**Comment by lidel** [comment]
https://github.com/ipfs/interface-go-ipfs-core/issues/55#issuecomment-1597759916
