### ISSUE TITLE
FileStat missing

### ISSUE THREAD

**Issue by dokterbob** [ipfs/interface-go-ipfs-core#58]
```golang
type FileStat struct {
    Cid cid.Cid
    Blocks int
    Size int
    CumulativeSize int
    Type FileType
}
```

As return value for proposed `UnixFs.Stat()`, see: https://github.com/ipfs/go-ipfs-http-client/issues/78

**Comment by Stebalien** [comment]
This is currently the case because there is no "ipfs stat" command and we haven't implemented the `ipfs files` API (#54).

However, we should probably just go ahead and expose that on the CoreAPI. However, I'd return the following:

```
type FileStat struct {
    Cid cid.Cid
    Size int // File size, if known. Otherwise -1.
    Type FileType
    Mode os.FileMode // coming in unixfsv1.5
    ModTime time.Time // coming in unixfsv1.5
}
```

Explicitly dropping things directly related to the underlying structure (non-cumulative size & number of direct children)

**Comment by dokterbob** [comment]
UnixFS 1.5!? What about 2? Is it finally coming? I'm getting worried. ;)

**Comment by lidel** [comment]
This repository is no longer maintained and has been copied over to [boxo/coreiface](https://github.com/ipfs/boxo/tree/main/coreiface) and [kubo/client/rpc](https://github.com/ipfs/kubo/tree/master/client/rpc).

 In an effort to avoid noise and crippling in the Boxo repo from the weight of issues of the past, we are closing most issues and PRs in this repo (https://github.com/ipfs/interface-go-ipfs-core/issues/55#issuecomment-1597759916).
 
 Please feel free to open a new issue in Boxo/Kubo (and reference this issue), explaining what types of examples should be added to https://github.com/ipfs/boxo/tree/main/examples.

You can learn more in the [FAQs for the Boxo repo copying/consolidation effort](https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ).
